# Test environment
#mongodb_hostname: payment-db
#mongodb_database_name: testPaymentDB

# Server properties
server:
  port: 8093

# Application properties
spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: optional:settings.yml
  profiles:
    active: standalone
# MongoDB properties
#  data:
#    mongodb:
#      database: testWorkingDB
#      host: localhost
#      port: 27017
