eureka_hostname: service-registry

service_hostname: payment-service

#mongodb_hostname: payment-db

# Production environment
#mongodb_database_name: paymentDB

# Development environment
#mongodb_database_name: devPaymentDB

# Test environment
#mongodb_database_name: testPaymentDB

# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_hostname}:8761/eureka
  instance:
    hostname: ${service_hostname}

# Server properties
server:
  port: 8093

# Application properties
spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: optional:settings.yml
# MongoDB properties
#  data:
#    mongodb:
#      database: testWorkingDB
#      host: localhost
#      port: 27017
