# Development environment

eureka_hostname: service-registry

service_hostname: payment-service

#mongodb_hostname: payment-db
#mongodb_database_name: devPaymentDB

# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_hostname}:8761/eureka
  instance:
    hostname: ${service_hostname}
