# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8093

# Application properties
spring:
  application:
    name: PAYMENT-SERVICE
# MongoDB properties
#  data:
#    mongodb:
#      database: testWorkingDB
#      host: localhost
#      port: 27017
